

# train and val data as 1) directory: path/images/, 2) file: path/images.txt, or 3) list: [path1/images/, path2/images/]
train: ["./data/brick/brick4x2/train.txt", "./data/brick/brick2x2/train.txt"]
val: ["./data/brick/brick4x2/test.txt", "./data/brick/brick2x2/test.txt"]
test: ["./data/brick/brick4x2/test.txt", "./data/brick/brick2x2/test.txt"]

mesh: ["./data/brick/brick4x2/brick4x2.ply", "./data/brick/brick2x2/brick2x2.ply"]
tr_range: ["./data/brick/brick4x2/training_range.txt", "./data/brick/brick2x2/training_range.txt"]
backup : ./backup/brick
names : ["brick4x2", "brick2x2"]

background_path: "./data/VOCdevkit/VOC2012/JPEGImages"
coords: 18

gpus : 0

nc: 2  # number of classes

fx: 949.8506622
fy: 949.70506462
u0: 627.84604663
v0: 354.06980147
